apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: ArtemLoboiko
spec:
  containers:
  - name: container-api
    image: tomcat:8.5.38
    ports:
      - containerPort: 8080

  - name: container-apache
    image: httpd:latest
    ports:
      - containerPort: 80

